### ISSUE TITLE
[DOCUMENTATION] Finish writing documentation

### ISSUE THREAD

**Issue by NADEE-MJ** [NADEE-MJ/finance_tracker_api#21]
**Context**

Switching to FastAPI has allowed for auto-documentation of all API endpoints and most usage, however, a basic setup/readme file is still required to document important info on the Github page itself. Although a proper readme and other documentation has been added, a lot of the actual content has still not been added.

The goal of this documentation is to help the reader get started with the finance_tracker_api not actually how to use all the endpoints as I had in the flask version of this API. All of the actual usage of the endpoints is in SwaggerUI and since I will most likely not be hosting this for widespread use, users will have to set this up themselves to see the endpoint documentaion.

**Tasks**

- [ ] Write about/screenshots of swaggerui in README.md
- [ ] Write setup/preqs in README.md
- [ ] Write usage in README.md
- [ ] Write setup dev environment in contributing
- [ ] Look over all docs one more time
