### ISSUE TITLE
[FEATURE] setup dockerfiles for creating docker containers

### ISSUE THREAD

**Issue by NADEE-MJ** [NADEE-MJ/finance_tracker_api#23]
**Context**

I would like to make an easy way to deploy the API to my server and containers seem like the best way to do this, I have considered doing something like this in the past however it seemed to be unnecessary, however now with how complicated the app is getting and using Postgres, it seems like the best option to deploy the API.

**Alternatives**

I can do this just by using pipenv and installing the dependencies on each machine I want to use and set up the environment every time, but making docker containers keeps all dependencies bundled so there are no big messes.

**Tasks**

- [ ] Update API for use with docker
- [ ] Set up a way to access alembic migrations with containers
- [ ] container for Postgres
- [ ] container for API
- [ ] documentation for how to set up container need to use Postgres container along with it
- [ ] add a release of the api container image

**Comment by NADEE-MJ** [comment]
Still in the testing phase with this, trying to figure out how docker works. I have setup up a server on my local network and am hosting this API on it. You can check it out while I am setting it up [here](https://api.nadee-mj.dev/docs). The API is still not fully functional, the API is working but is not able to connect to the database. 

A lot of this is still in the testing phase and I don't really have anything to push to a branch yet since I just have a bunch of dangling files everywhere between my windows pc that I develop on and the debian server, but once I consolidate everything I will get around to pushing the updates to a working branch along with adding a v0.1 release of the container with some instructions on how to set it up.
